#!name=Apple WLOC Location Spoofer
#!desc=Modify the coordinates returned by Apple's network-based location service (Shadowrocket) | Shortcuts (recommended): Set Location https://www.icloud.com/shortcuts/182f3a014597468eb1b15b99261cdf22
#!author=Yu9191 Rewrite
#!homepage=https://github.com/sodardyjiber/wloc
#!icon=https://raw.githubusercontent.com/sodardyjiber/wloc/refs/heads/main/wloc.jpg
#!category=Tools

[Script]
Apple WLOC = type=http-response,pattern=^https?:\/\/gs-loc(-cn)?\.apple\.com\/clls\/wloc,requires-body=1,binary-body-mode=1,max-size=0,timeout=30,script-path=https://raw.githubusercontent.com/sodardyjiber/wloc/refs/heads/main/dist/wloc.js
WLOC Settings = type=http-request,pattern=^https?:\/\/gs-loc(-cn)?\.apple\.com\/wloc-settings\/save,requires-body=0,max-size=0,timeout=10,script-path=https://raw.githubusercontent.com/sodardyjiber/wloc/refs/heads/main/dist/wloc-settings.js

[MITM]
hostname = %APPEND% gs-loc.apple.com, gs-loc-cn.apple.com
